services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kochbuch
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/kochbuch
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data: