services:

  # Client

  client:
    build:
      context: ./client
      target: production
    labels:
      traefik.http.routers.client.rule: Host(`localhost`)
      traefik.http.services.client.loadbalancer.server.port: 80