services:

  # Client

  client:
    build:
      context: ./client
      target: development
    labels:
      traefik.http.routers.client.rule: Host(`localhost`)
      traefik.http.services.client.loadbalancer.server.port: 5173



  # pgAdmin

  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=login@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=5004
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    labels:
      traefik.http.routers.pgadmin.rule: Host(`db.localhost`)
      traefik.http.services.pgadmin.loadbalancer.server.port: 5004

volumes:
  pgadmin_data: