services:

  # Proxy
  
  proxy:
    image: traefik:v3.7
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Database

  db:
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kochbuch
    volumes:
      - postgres_data:/var/lib/postgresql



  # Backend

  backend:
    build: ./backend
    restart: always
    develop:
      watch:
        - path: ./backend
          action: sync+restart
          target: /app
        - path: ./backend/package.json
          action: rebuild
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_HOST=db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_DB=kochbuch
      - PORT=5001
    depends_on:
      - db
    labels:
      traefik.http.routers.backend.rule: Host(`localhost`) && PathPrefix(`/api`)
      traefik.http.services.backend.loadbalancer.server.port: 5001



  # Client
  
  client:
    build:
      context: ./client
      target: production
    restart: always
    develop:
      watch:
        - path: ./client
          action: sync
          target: /app
        - path: ./client/package.json
          action: rebuild
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true



volumes:
  postgres_data: